# If you ever see the error below:
# [ SYMPTOM: ]
#   File "/home/gkimetto/gk-sandbox/PYTHON/General Practice/Kwargs_Args.py", line 1
# SyntaxError: Non-ASCII character '\xe2' in 
# file /home/gkimetto/gk-sandbox/PYTHON/General Practice/Kwargs_Args.py on line 1, 
# but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details


"""# -*- coding: utf-8 -*-"""